### ISSUE TITLE
Social share sites not recognizing meta tags

### ISSUE THREAD

**Issue by sreahard** [kodyl/react-document-meta#24] opened 2016-08-16 17:42 UTC
The meta tags are being generated properly in my doc head, but when I run the urls through various debuggers to get the scrape data it doesn't find the meta tags. 

Using Facebook debugger: http://developers.facebook.com/tools/debug
Google data testing tool: http://www.google.com/webmasters/tools/richsnippets
Twitter card validator: https://dev.twitter.com/docs/cards/validation/validator

**Comment by danieljuhl** [comment] 2016-08-17 06:26
Are you using server-side rendering? Otherwise it won't work..

**Comment by sreahard** [comment] 2016-08-17 21:03
I am not, my server-side is rendered in .NET so I'll have to figure out how to make it work. Thanks.

**Comment by danieljuhl** [comment] 2016-08-18 07:42
The problem is, that the social medias are looking at the HTML returned from you server, and doesn't execute JS. So the meta tags has to be in the initial server render.

**Comment by danieljuhl** [comment] 2016-08-18 07:42
I'm closing for now..

**Closed by danieljuhl** 2016-08-18 07:42 UTC
