### ISSUE TITLE
Meta tags not changing 

### ISSUE THREAD

**Issue by stanleycyang** [kodyl/react-document-meta#15] opened 2016-01-10 07:31 UTC
I plugging in my data into the metaData:

```js

    let metaData = {
      title: aTutorial.headline,
      description: aTutorial.description,
      canonical: `https://www.stanleycyang.com${this.props.location.pathname}`,
      meta: {
        charset: 'utf-8',
        name: {
          keywords: keywordStr
        }
      }
    }

...

  return (
    <main>
        <DocumentMeta {...metaData} />
       ...
    </main>
  )
```

It doesn't change my meta data (`description`, `keywords`, etc). Not sure what I'm doing wrong.

**Comment by danieljuhl** [comment] 2016-01-10 08:39
Can you please provide a full re-producible case. It's very hard to investigate a possible issue with a partial sample.

**Comment by stanleycyang** [comment] 2016-01-10 18:58
It's in a private repo, however it's simply make an AJAX call for the tutorial then loading it in:

```js
'use strict'

import React, { Component, PropTypes } from 'react'
import DocumentMeta from 'react-document-meta'

// Replace this with your AJAX call
import { showTutorial} from '../../../redux/actions/tutorials'


export default class Page extends Component {

  constructor(props) {
    super(props)
  }

  componentWillMount() {
    const { headline } = this.props.params

    // Show tutorial in an AJAX call
    dispatch(showTutorial(headline, false))
  }

  render() {
    const { Tutorial } = this.props.appState

    let metaData = {
      title: Tutorial.headline,
      description: Tutorial.description,
      meta: {
        charset: 'utf-8',
        name: {
          keywords: Tutorial.keywordStr
        }
      }
    }

    return (
      <main>
        {/* Document meta */}
        <DocumentMeta {...metaData} />
      </main>
    )
  }
}
```

I'm using Redux for the dispatch call, but that can be replaced with a `fetch` polyfill

**Comment by danieljuhl** [comment] 2016-01-14 10:54
I'm not able to reproduce this error, and I've just modified to client-side example to show, that the module works. It must be a problem somewhere else in your code. If the error really is related to `react-document-meta`, please provide a complete reproducible case. I'm closing this issue for now.

**Closed by danieljuhl** 2016-01-14 10:54 UTC

**Comment by stanleycyang** [comment] 2016-01-14 17:17
@danieljuhl If you provide static meta tags in the HTML `<head>`, then it prevents the the react-document-meta from working correctly (tested it out in the client-side code). Thanks for looking at it!

**Comment by danieljuhl** [comment] 2016-01-14 21:12
So you have some static pre defined meta tags, that you expect the module to overwrite? It's is designed to only work on meta tags defined by the module, to allow for predefined tags
